//
// Author: Ido Shapira
// date: 03/08/2021
//
var ctx = null;
var canvas = null;
var gameMap = [
	0, 0, 0, 0, 0, 0, 0,
	0, 1, 1, 1, 1, 1, 0,
	0, 1, 1, 1, 1, 1, 0,
	0, 1, 1, 1, 1, 1, 0,
	0, 1, 1, 1, 1, 1, 0,
	0, 1, 1, 1, 1, 1, 0,
	0, 0, 0, 0, 0, 0, 0,
];
var gameStatus = {
	inProgress: true,
	ended: false,
	stoped: false
}
const numOfPlaints = 2;

var tileW = 50, tileH = 50;
var mapW = 7, mapH = 7;
var currentSecond = 0, frameCount = 0, framesLastSecond = 0, lastFrameTime = 0;

                    // tileFrom , tileTo, timeMoved, dimensions, position, delayMove, icon
var human_player = new Player([5,1], [5,1], 0, [30,30], [260,60], 500, "red_agent.png");
initializeFirebase();
var computer_player = new Player([1,1], [1,1], 0, [30,30], [60,60], 500, "blue_agent.png");
var computer_controller = new PlayerController(computer_player, "random");
// firebase.database().ref("chosen-controller").once('value',
//     (snap) => {
//         selectedBehavior = snap.val();
//         computer_controller = new PlayerController(computer_player, selectedBehavior);

// 		var type = computer_controller.getType();
//         // Generate a reference to a new location and add some data using push()
//         var newPostRef = firebase.database().ref("all-games").push({
//             behavior: type
//         });
//         // Get the unique ID generated by push() by accessing its key
//         postID = newPostRef.key;
//         // console.log("postID: "+postID);
//     });

var stag = new Player([3,3], [3,3], 0, [30,30], [150,150], 500, "stag.png");
stag_controller = new StagController(stag, "random");

function position(tile, dimensions)
{
	return [Math.round((tile[0] * tileW) + ((tileW-dimensions[0])/2)),
			Math.round((tile[1] * tileH) + ((tileH-dimensions[1])/2))];
}

function randomValidTiles(n) {
	var indexs = []; // find valid indexes
	gameMap.filter(function(elem, index, array){
		if(elem == 1) {
			var i = Math.floor(index / mapW);
			var j = index % mapH;
			if(j != computer_player.tileFrom[0] && i != computer_player.tileFrom[1]
				&& j != human_player.tileFrom[0] && i != human_player.tileFrom[1]
				&& j != stag.tileFrom[0] && i != stag.tileFrom[1]) {
					// award can not be in player tile
				indexs.push([j,i]);
			}
		}
	});
	var result = [];
	// choose randomly n indexs
	for (var i = 0; i < n; i++) {
		var idx = Math.floor(Math.random() * indexs.length);
		result.push(indexs[idx]);
		indexs.splice(idx, 1);
	}
	return result;
}

var shrubs = [];
var validTiles = randomValidTiles(numOfPlaints);
for(var i=0; i<numOfPlaints; i++) {
	shrubs.push(new Shrub(validTiles[i], [15,15], position(validTiles[i], [15, 15]), 0.05, 5, "plant_fruit.png"));
}

var human_shrubs = [];
var computer_shrubs = [];

function toIndex(x, y)
{
	return((y * mapW) + x);
}

function zeros(dimensions) { // dimensions = [r,c] 
    var array = [];
    for (var i = 0; i < dimensions[0]; ++i) {
        array.push(dimensions.length == 1 ? 0 : zeros(dimensions.slice(1)));
    }
    return array;
}

var prev_state = [[], zeros([mapW, mapH]), zeros([mapW, mapH]), [], [], []];
prev_state[1][human_player.tileFrom[1]][human_player.tileFrom[0]] = 1;
prev_state[2][computer_player.tileFrom[1]][computer_player.tileFrom[0]] = 1;

function getBoardState() {
	var state = [
			[], // the board
			[], // human trace
			[], // computer trace
			//zeros([mapW, mapH]), // Shrubs collected by human
			//zeros([mapW, mapH]), // Shrubs collected by computer
			zeros([mapW, mapH]) // all Shrubs
			];
	
	var board = gameMap.slice();
	while(board.length) state[0].push(board.splice(0,10)); // reshape board

	//human trace
	for(var i=0; i<prev_state[1].length; i++) {
		state[1].push(prev_state[1][i].map(x => Number((x * 0.9).toFixed(2))));
	}
	state[1][human_player.tileFrom[1]][human_player.tileFrom[0]] = 1;
	//computer trace 
	for(var i=0; i<prev_state[2].length; i++) {
		state[2].push(prev_state[2][i].map(x => Number((x * 0.9).toFixed(2))));
	}
	state[2][computer_player.tileFrom[1]][computer_player.tileFrom[0]] = 1;

	// //human collected Shrubs
	// for(shrub of human_shrubs) {
	// 	state[3][shrub.tile[1]][shrub.tile[0]] = 1;
	// }
	// //computer collected Shrubs
	// for(shrub of computer_shrubs) {
	// 	state[4][shrub.tile[1]][shrub.tile[0]] = 1;
	// }

	//allShrubs
	for(shrub of shrubs) {
		state[3][shrub.tile[1]][shrub.tile[0]] = 1;
	}
	prev_state = state.slice();	
	return state;
}

var humanMove = null;
var computerMove = null;
var handleKeyUp = function(e) {
	if(e.keyCode>=37 && e.keyCode<=40) {
		var currentFrameTime = Date.now();
		if((currentFrameTime-human_player.timeMoved>=human_player.delayMove)) {
			var validHumanAction = false;
			switch(e.keyCode) {
				case 37:
					if(human_player.tileFrom[0]>0 && gameMap[toIndex(human_player.tileFrom[0]-1, human_player.tileFrom[1])]==1) {
						human_player.tileTo[0]-= 1; //left
						validHumanAction = true;
						humanMove = e.keyCode;
					}
					break;
				case 38:
					if(human_player.tileFrom[1]>0 && gameMap[toIndex(human_player.tileFrom[0], human_player.tileFrom[1]-1)]==1) {
						human_player.tileTo[1]-= 1; //up
						validHumanAction = true;
						humanMove = e.keyCode;
					}
					break;
				case 39:
					if(human_player.tileFrom[0]<(mapW-1) && gameMap[toIndex(human_player.tileFrom[0]+1, human_player.tileFrom[1])]==1) {
						human_player.tileTo[0]+= 1; //right
						validHumanAction = true;
						humanMove = e.keyCode;
					}
					break;
				case 40:
					if(human_player.tileFrom[1]<(mapH-1) && gameMap[toIndex(human_player.tileFrom[0], human_player.tileFrom[1]+1)]==1) {
						human_player.tileTo[1]+= 1; //down
						validHumanAction = true;
						humanMove = e.keyCode;
					}
					break;
			}
			human_player.timeMoved = currentFrameTime;
			if (humanMove != null) {
				human_player.keysDown[humanMove] = true;
			}

			if(validHumanAction) {
				//blue player move
				var state = getBoardState();
				saveToFirebase(state, humanMove);
				computerMove = computer_controller.move(state);
				computer_player.keysDown[computerMove] = true;

				// the stag either moves towards the nearest agent (default) or takes a random move.
				stagMove = stag_controller.move(state);
				stag.keysDown[stagMove] = true;
			}
		}
	}
}
window.onload = function()
{
	canvas = document.getElementById('game');
	ctx = canvas.getContext("2d");
	requestAnimationFrame(drawGame);
	ctx.font = "bold 10pt sans-serif";

	window.addEventListener("keyup", handleKeyUp);
};

function drawGame()
{
	if(ctx==null) { return; }

	var currentFrameTime = Date.now();
	var timeElapsed = currentFrameTime - lastFrameTime;
	
	var sec = Math.floor(Date.now()/1000);
	if(sec!=currentSecond)
	{
		currentSecond = sec;
		framesLastSecond = frameCount;
		frameCount = 1;
	}
	else { frameCount++; }

	if(!human_player.processMovement(currentFrameTime)) //move human player on board
	{
		human_player.keysDown[humanMove] = false;

		if(human_player.tileFrom[0] != human_player.tileTo[0] || human_player.tileFrom[1] != human_player.tileTo[1])
		{ human_player.timeMoved = currentFrameTime; }
	}
	

	if(!computer_player.processMovement(currentFrameTime)) //move computer player on board
	{
		if(computer_player.keysDown[38] && computer_player.tileFrom[1]>0 && gameMap[toIndex(computer_player.tileFrom[0], computer_player.tileFrom[1]-1)]==1) { computer_player.tileTo[1]-= 1; }
		else if(computer_player.keysDown[40] && computer_player.tileFrom[1]<(mapH-1) && gameMap[toIndex(computer_player.tileFrom[0], computer_player.tileFrom[1]+1)]==1) { computer_player.tileTo[1]+= 1; }
		else if(computer_player.keysDown[37] && computer_player.tileFrom[0]>0 && gameMap[toIndex(computer_player.tileFrom[0]-1, computer_player.tileFrom[1])]==1) { computer_player.tileTo[0]-= 1; }
		else if(computer_player.keysDown[39] && computer_player.tileFrom[0]<(mapW-1) && gameMap[toIndex(computer_player.tileFrom[0]+1, computer_player.tileFrom[1])]==1) { computer_player.tileTo[0]+= 1; }
		computer_player.keysDown[computerMove] = false;

		if(computer_player.tileFrom[0]!=computer_player.tileTo[0] || computer_player.tileFrom[1]!=computer_player.tileTo[1])
		{ computer_player.timeMoved = currentFrameTime; }
	}

	if(!stag.processMovement(currentFrameTime)) //move stag on board
	{
		if(stag.keysDown[38] && stag.tileFrom[1]>0 && gameMap[toIndex(stag.tileFrom[0], stag.tileFrom[1]-1)]==1) { stag.tileTo[1]-= 1; }
		else if(stag.keysDown[40] && stag.tileFrom[1]<(mapH-1) && gameMap[toIndex(stag.tileFrom[0], stag.tileFrom[1]+1)]==1) { stag.tileTo[1]+= 1; }
		else if(stag.keysDown[37] && stag.tileFrom[0]>0 && gameMap[toIndex(stag.tileFrom[0]-1, stag.tileFrom[1])]==1) { stag.tileTo[0]-= 1; }
		else if(stag.keysDown[39] && stag.tileFrom[0]<(mapW-1) && gameMap[toIndex(stag.tileFrom[0]+1, stag.tileFrom[1])]==1) { stag.tileTo[0]+= 1; }
		stag.keysDown[computerMove] = false;

		if(stag.tileFrom[0]!=stag.tileTo[0] || stag.tileFrom[1]!=stag.tileTo[1])
		{ stag.timeMoved = currentFrameTime; }
	}

	//check for eaten Shrubs
	for(var i=0; i<shrubs.length; i++) {
		temp_shrub = shrubs[i];
		if(temp_shrub.tile[0] == human_player.tileFrom[0] && temp_shrub.tile[1] == human_player.tileFrom[1]) {
			shrubs.splice(i, 1);
			human_player.score = human_player.score + temp_shrub.value;
			human_player.scoreToView = human_player.scoreToView + temp_shrub.valueToView;
			if(human_player.tileFrom[0] == computer_player.tileFrom[0] && human_player.tileFrom[1] == computer_player.tileFrom[0]) {
				computer_player.score = computer_player.score + shrub.value;
				computer_player.scoreToView = computer_player.scoreToView + shrub.valueToView;
				computer_shrubs.push(temp_shrub);
			}
			human_shrubs.push(temp_shrub);
		}
		if(temp_shrub.tile[0] == computer_player.tileFrom[0] && temp_shrub.tile[1] == computer_player.tileFrom[1]) {
			shrubs.splice(i, 1);
			computer_player.score = computer_player.score + temp_shrub.value;
			computer_player.scoreToView = computer_player.scoreToView + temp_shrub.valueToView;
			if(human_player.tileFrom[0] == computer_player.tileFrom[0] && human_player.tileFrom[1] == computer_player.tileFrom[0]) {
				// two player got to the Shrub at the same time
				human_player.score = human_player.score + shrub.value;
				human_player.scoreToView = human_player.scoreToView + shrub.valueToView;
				human_shrubs.push(temp_shrub);
			}
			computer_shrubs.push(temp_shrub);
			
		}
	}

	if(shrubs.length == 0 && gameStatus.inProgress) { 
		// game ended when their is no shrubs on board
		gameStatus.inProgress = false;
		gameStatus.ended = true;
	}

	if(gameStatus.ended) {
		gameStatus.ended = false;
		gameStatus.stoped = true;

		human_player.score = human_player.score + human_player.scores.finish;
		human_player.scoreToView = human_player.scoreToView + human_player.scoresToView.finish;

		computer_player.score = computer_player.score + computer_player.scores.finish;
		computer_player.scoreToView = computer_player.scoreToView + computer_player.scoresToView.finish;
		
		console.log('1) Computer score: '+ computer_player.scoreToView);
		console.log('2) Computer score: '+ computer_player.score);
		console.log('1) Human score: '+ human_player.scoreToView);
		console.log('2) Human score: '+ human_player.score);
		window.removeEventListener("keyup", handleKeyUp);

		finishGame(getBoardState(), humanMove); //sending the last state // TODO: Check this carefuly
	}


	// draw objects:
	
	for(var y = 0; y < mapH; ++y) // draw the board
	{
		for(var x = 0; x < mapW; ++x)
		{
			switch(gameMap[((y*mapW)+x)])
			{
				case 0:
					ctx.fillStyle = "#685b48"; // color: brown
					break;
				default:
					ctx.fillStyle = "#C4A484"; // color: light brown
			}

			ctx.fillRect( x*tileW, y*tileH, tileW, tileH);
		}
	}
	
	var borderWidth = 1;   
	var offset = borderWidth * 2;
	
	for(shrub of shrubs) {
		ctx.drawImage(shrub.iconImage, shrub.position[0] - borderWidth, shrub.position[1] -borderWidth, shrub.dimensions[0] + offset, shrub.dimensions[1] + offset);
	}
	ctx.drawImage(computer_player.iconImage, computer_player.position[0] - borderWidth, computer_player.position[1] -borderWidth, computer_player.dimensions[0] + offset, computer_player.dimensions[1] + offset);
	ctx.drawImage(human_player.iconImage, human_player.position[0] - borderWidth, human_player.position[1] -borderWidth, human_player.dimensions[0] + offset, human_player.dimensions[1] + offset);

	ctx.drawImage(stag.iconImage, stag.position[0] - borderWidth, stag.position[1] -borderWidth, stag.dimensions[0] + offset, stag.dimensions[1] + offset);

	ctx.fillStyle = "#0000ff"; // title color: blue
	ctx.fillText("Blue score: " + computer_player.scoreToView, 20, 25);
    ctx.fillText("Blue action: " + computer_player.codeToAction[computerMove], 20, 335);

	ctx.fillStyle = "#ff0000"; // title color: red
	ctx.fillText("Red score: " + human_player.scoreToView, 245, 25);
	ctx.fillText("Red action: " + human_player.codeToAction[humanMove], 245, 335);

	lastFrameTime = currentFrameTime;
	requestAnimationFrame(drawGame);
}
